FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    git \
    curl \
    ffmpeg \
    espeak-ng \
    make \
    g++ \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    torch transformers torchaudio soundfile numpy \
    kokoro misaki pyopenjtalk \
    fugashi unidic-lite jaconv \
    mojimoji

WORKDIR /app/python

CMD ["python", "main.py"]