services:

  web:
    container_name: deven_web
    build: ./docker/web
    restart: always
    ports: ["${HTTP_PORT}:80"]
    volumes:
      - ${APP_ROOT}:/sites
      - ./deven-sys:/deven-sys
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  db:
    container_name: deven_db
    image: mariadb:latest
    restart: always
    volumes:
      - ${APP_ROOT}:/sites
      - ./deven-sys:/deven-sys
    ports: ["${MARIADB_PORT}:3306"]
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  adminer:
    container_name: deven_adminer
    image: adminer:latest
    restart: always
    ports: ["${ADMINER_PORT}:8080"]
