#!/usr/bin/env bash



function getDir() {
  local dir
  dir="$(dirname "$(readlink "$0")")"
  echo "$dir"
}
trim() {
  local __in="$1"
  printf '%s' "$__in" | sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//'
}


COMMAND=$1
ARG1=$2
. "$(getDir)/.env"


case "$COMMAND" in
""|help)
  echo "Help"
  ;;
version)
  echo "1"
  ;;
cd)
  echo "$(getDir)"
  ;;
build)
  docker compose up --build -d
  ;;
stop)
  docker compose stop
  ;;
restart)
  docker compose stop
  docker compose up -d
  ;;
ps)
  docker ps | grep deven
  ;;
list)
  file="$(getDir)/docker/web/apache/sites.conf"
  while IFS= read -r line; do
    [[ -z $line ]] && continue
    read -ra parts <<< "$line"
    port="$(trim "$HTTP_PORT")"
    echo "- http://${parts[2]}:$port/ -> ${parts[3]}"
  done < "$file"
  ;;
edit)
  file="$(getDir)/docker/web/apache/sites.conf"
  vim "$file"
  ;;
bash)
  if [ -z "$ARG1" ]; then
    container="deven_web"
  else
    container="deven_$ARG1"
  fi
  docker exec -it "$container" bash
  ;;
*)
  echo "░█ Command not found."
  ;;
esac