FROM php:8.4-apache

RUN apt-get update && apt-get install -y \
    git unzip wget curl mariadb-client ffmpeg libmagickwand-dev \
    && docker-php-ext-install pdo pdo_mysql

RUN git clone https://github.com/Imagick/imagick.git --depth 1 /tmp/imagick && \
    cd /tmp/imagick && \
    git fetch origin master && \
    git switch master && \
    cd /tmp/imagick && \
    phpize && \
    ./configure && \
    make && \
    make install && \
    docker-php-ext-enable imagick

# PHP-imap
# RUN apt-get install -y libc-client2007e-dev libkrb5-dev libssl-dev
# RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
#     && docker-php-ext-install -j"$(nproc)" imap

# Cleanup apt
RUN rm -rf /var/lib/apt/lists/* && apt-get clean

RUN a2enmod rewrite macro

COPY apache/macro-site.conf /etc/apache2/conf-available/macro-site.conf

RUN a2enconf macro-site
RUN a2dissite 000-default
RUN echo "Include /etc/apache2/sites.conf" >> /etc/apache2/apache2.conf

WORKDIR /sites

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

EXPOSE 80
CMD ["apache2-foreground"]